### ISSUE TITLE
1.3.10 New: GeoFence plugins

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#16]
Version to match Geoserver version; enables granular role based auth/authz to Geoserver components
![image](https://github.com/user-attachments/assets/81b829ce-f7bd-4299-91bd-bc3bcdaea39c)

**Comment by voogt** [comment]
Hi @tinashechiraya when I vistit this url localhost:8080/geoserver/rest/about/version.xml I dont see geofence listed
![Image](https://github.com/user-attachments/assets/a200b498-8b08-47da-ab09-d9d7da0aa2ab)

**Comment by tinashechiraya** [comment]
![Image](https://github.com/user-attachments/assets/4372f9a6-ffad-43c6-b788-22f4f9788c25)

from the logs @voogt

**Comment by Brennan-Walsh** [comment]
This has been installed
