### ISSUE TITLE
1.7.1 Upgrade Keycloak Container

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#20]
![image](https://github.com/user-attachments/assets/d1991b35-27eb-4d85-8c20-ce3159edacc1)

**Comment by Brennan-Walsh** [comment]
![Image](https://github.com/user-attachments/assets/8bb00628-59ae-4abf-a311-9fd65e6f96a8)

https://mapstack-uat.geoint.africa/auth/
The latest versio of keycloak has been added and is accessible
