### ISSUE TITLE
1.7.2 New: Provision components for SSO from Azure

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#21]
![image](https://github.com/user-attachments/assets/40475935-478c-43db-b742-7f2f06cfe486)

**Comment by Brennan-Walsh** [comment]
![Image](https://github.com/user-attachments/assets/dbc145ff-ed59-4e48-a2bb-6791f9302418)

**Comment by Brennan-Walsh** [comment]
![Image](https://github.com/user-attachments/assets/35e9d377-ada8-45ee-93fd-88b35f85d949)

**Comment by Brennan-Walsh** [comment]
90% there, there seems to be a URI redirect issue between keycloak and geoserver - Juanique @ kartoza has been notified and is currently working on the resolution
