### ISSUE TITLE
1.8	Documentation and Release Notes

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#22]
Documentation on infrastructure setup and managment process, release notes to describe changes
![image](https://github.com/user-attachments/assets/836ece8f-ad84-498e-9b35-43e49e15fd4a)

**Comment by Brennan-Walsh** [comment]
Please check the Mapstore-Builder-V2 documentation.  Currently it does not contain the setup process unless it is somewhere else in folder 
![Image](https://github.com/user-attachments/assets/8d6effc2-84b2-4941-b895-3d0211661bc1)

**Comment by voogt** [comment]
Hi @Brennan-Walsh I've updated the read me in the development branch for both mapstack-infra repo and mapstore-builder repo to be more descriptive

**Comment by Brennan-Walsh** [comment]
Must include trouble shouting section. 95% done . 

Documents are available in the correct location now.
