### ISSUE TITLE
2.1.3 Upgrade Database set up per Mapstack instance for MapStore artefacts

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#29]
![image](https://github.com/user-attachments/assets/ed2f8897-78f8-4933-93bc-54070923ae16)

**Comment by tinashechiraya** [comment]
linked to #54 @voogt Once the mapstack instance is set then we trigger building a database for it. The script is already there create_org.sh

**Comment by voogt** [comment]
Hi @tinashechiraya so this ticket can be moved to client for testing?

**Comment by tinashechiraya** [comment]
Yes ,just that it's a manual process where , they have to enter the postgres container and execute that script to build the database @voogt

**Comment by Brennan-Walsh** [comment]
Done and tested
