### ISSUE TITLE
2.1.6 Public database tables linked to all organisational Databses via postgres_fdw at creation of organisational database

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#31]
![image](https://github.com/user-attachments/assets/a11b2551-39c8-4372-b068-02c7b251d29e)

**Comment by mvmaltitz** [comment]
Add a Provencal boundary for testing purposes

**Comment by tinashechiraya** [comment]
Hi @mvmaltitz ,can you provide more context here 'Add a Provencal boundary for testing purposes'?

**Comment by tinashechiraya** [comment]
provincial boundary ...viewable and accessible
@Jeremy-Prior or @seabilwe ... I will ping you
