### ISSUE TITLE
2.5 Reverse Proxy Setup

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#37]
- [x] LetsEncrypt certificates to allow HTTPS
- [x] Nginx to reverse proxy geoserver
- [x] Nginx to reverse proxy mapstore instances
- [x] Nginx to reverse proxy Keycloak
- [x] Nginx to reverse proxy Zoo WPS
- [x] Nginx to reverse proxy SuperSets Dashboards
![image](https://github.com/user-attachments/assets/7fb01143-e0b0-44cf-82bb-cb1207998630)

**Comment by mvmaltitz** [comment]
_Nginx to reverse proxy SuperSets Dashboards_ can only be completed after 4.3 is complete

**Comment by tharanathkartoza** [comment]
Reverse proxy has been set up for geoserver, zoo wps and zoo api

**Comment by Brennan-Walsh** [comment]
geoserver logout 
super logout 

geoserver roles and groups

**Comment by voogt** [comment]
Hi @Brennan-Walsh superset logout and geoserver roles and group are working now. I'm still debugging geoserver logout
