### ISSUE TITLE
3.1 Activate Keycloak security with Microsoft

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#39]
![image](https://github.com/user-attachments/assets/cb88f5fe-975b-49d3-8d02-55435c567a66)

**Comment by mvmaltitz** [comment]
Received details via email

**Comment by Brennan-Walsh** [comment]
Where do we get the credientials from? 

AZURE_AD_CLIENT_ID=
AZURE_AD_CLIENT_SECRET=
AZURE_AD_AUTH_URL=
AZURE_AD_TOKEN_URL=

**Comment by voogt** [comment]
Hi @Brennan-Walsh I created an app on microsoft azure which can be accessed here https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/Overview/appId/ccb5b2e2-68a8-48d8-a477-24f58c060121/objectId/c3372dbc-a807-45cf-9d98-3f608fb6f531/isMSAApp~/false/defaultBlade/Overview/appSignInAudience/AzureADMyOrg/servicePrincipalCreated~/true Please remember to change the redirect uri's currently configured to the url which keycloak can be accessed
![image](https://github.com/user-attachments/assets/be63a8bb-263b-49b6-b434-d8310c994ff4)
