### ISSUE TITLE
3.3 Keycloak account to work with geoserver

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#40]
![image](https://github.com/user-attachments/assets/92beee75-d8a1-4e29-90fc-834f051a1220)

**Comment by Brennan-Walsh** [comment]
We have tested the and redirect is curently not redirect to the correct location

![Image](https://github.com/user-attachments/assets/6c39d132-7d1c-4cad-aac3-3814d126ec49)

**Comment by voogt** [comment]
Hi @Brennan-Walsh I added the admin role for geoserver to you and Kaylan in keycloak. Can you try again please?
![image](https://github.com/user-attachments/assets/2b96c383-709b-453e-9444-90dea4cb7d95)

**Comment by Brennan-Walsh** [comment]
Can now login with Azure

***@***.***

Logout

Take me here.

***@***.***

Brennan Walsh

Senior Geospatial Data Engineer and Analyst
Direct: +27 83 694 8572<tel:+27%20836948572>
Email: ***@***.******@***.***>
Web: www.geoint.africa <https://geoint.africa/>
View our privacy policy here<https://geoint.africa/wp-content/uploads/2023/07/GeoINT_Privacy_Policy_23.pdf>
View our PAIA and POPIA here<https://geoint.africa/wp-content/uploads/2023/07/PAIA-Manual.pdf>
[LinkdIn Logo]<https://www.linkedin.com/company/geo-intelligence-corp/>
[Geoint Company Logo]
