### ISSUE TITLE
4.1 Upgrade to the latest Mapstore2 Version  2024.02.00&nbsp;

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#43]
![image](https://github.com/user-attachments/assets/8c0fe4bd-6b36-4642-ab80-7bcfe4103d56)

**Comment by mvmaltitz** [comment]
Please note this must be the latest version that was released 4 days ago

**Comment by Brennan-Walsh** [comment]
keycloak url looks incorrect  on login page 

![Image](https://github.com/user-attachments/assets/2a63d2af-1b2f-4df7-a9d6-063dba7fcdca)

**Comment by Brennan-Walsh** [comment]
Basemaps not loading 

![Image](https://github.com/user-attachments/assets/5350ca0b-e037-42e7-8cfe-11118beac95d)

**Comment by Brennan-Walsh** [comment]
dropdown on catalog page not showing correctly 

![Image](https://github.com/user-attachments/assets/e8683557-4cc3-4d84-8ea9-7731941305a7)

**Comment by Brennan-Walsh** [comment]
print button not showing on new map

![Image](https://github.com/user-attachments/assets/25267085-6b99-4827-ac7f-405d2dfed8ed)

**Comment by Brennan-Walsh** [comment]
the style button keeps asking us to login . 

![Image](https://github.com/user-attachments/assets/37fc85bc-86b8-4d6b-8758-4b50d0a740d2)

**Comment by Brennan-Walsh** [comment]
not able to see the new features in the edit template section 
![Image](https://github.com/user-attachments/assets/9cd65aaa-c206-47b1-ba76-4a53c02cb5d4)

this is the new option in mapstore2
![Image](https://github.com/user-attachments/assets/0c409bde-0718-4fa4-9edb-5e1d40802afb)

**Comment by Brennan-Walsh** [comment]
basemaps options are not available. 
![Image](https://github.com/user-attachments/assets/86c57f71-49a6-4b58-b9d5-d7a5ec7766f0)

**Comment by Brennan-Walsh** [comment]
The setting option show be available  and also the map legend show look like the example below. 

![Image](https://github.com/user-attachments/assets/cb1a0442-18c9-49cd-84d8-f3bacaaefbee)

**Comment by Brennan-Walsh** [comment]
geostory does not have the new layout

![Image](https://github.com/user-attachments/assets/b8d37fb4-c369-4e80-b0fe-1dd5ab001129)

new version. 

![Image](https://github.com/user-attachments/assets/cc3148ae-8719-455f-9dda-4f21ec11ac29)

**Comment by Brennan-Walsh** [comment]
geostory home button is taking up space on the menu bar . 

![Image](https://github.com/user-attachments/assets/c6602d09-915f-4034-a259-39fcbdf4a33c)

new version 
![Image](https://github.com/user-attachments/assets/2ecb8973-1b55-43ed-b686-8bcb65d3b075)

**Comment by Brennan-Walsh** [comment]
We are see the 2024.02 changes

**Comment by Brennan-Walsh** [comment]
There is a number of place where the box should be on the left and is in the incorrect location covering text. 
![Image](https://github.com/user-attachments/assets/fb7efe1c-4dcd-4a04-b1dc-ef25f2bed43c)

![Image](https://github.com/user-attachments/assets/299f2ef2-c887-4ce4-904b-69659a5c6347)

![Image](https://github.com/user-attachments/assets/aff74dfb-5fdc-4c54-a473-c35c2c01fe6c)

**Comment by Brennan-Walsh** [comment]
please compare the current language file to the new mapstack version file as is is missing a number of text labels. 

example  geprocessing 
![Image](https://github.com/user-attachments/assets/676a8ad2-9d2d-49af-a985-195adf10127b)
![Image](https://github.com/user-attachments/assets/98b1f25f-ff88-4f75-88a2-59d09dc0fc8b)

**Comment by Brennan-Walsh** [comment]
![Image](https://github.com/user-attachments/assets/1dedc5c3-3818-4d74-9c22-7763086a3d8d)

**Comment by Brennan-Walsh** [comment]
IF you update the laguange file these error should correct with the correct labels

**Comment by Brennan-Walsh** [comment]
Here is the updated language file 

[[Mapstack-data.en-US.json](https://github.com/user-attachments/files/17718048/Mapstack-data.en-US.json)
](url)
