### ISSUE TITLE
4.2 KeyCloak Login Page

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#44]
![image](https://github.com/user-attachments/assets/e02513ff-7eed-4be9-9b78-7a4951c8e46f)

**Comment by voogt** [comment]
Added custom login page
![Image](https://github.com/user-attachments/assets/3247b632-84f0-4b23-be73-b24426209fa6)

**Comment by Brennan-Walsh** [comment]
keycloak login page not showing on mapstack login page 

![Image](https://github.com/user-attachments/assets/7a812adc-c4b3-489f-8faa-425ce2bd43bc)

![Image](https://github.com/user-attachments/assets/26898dab-768a-4a74-a9ad-436950ccf032)

**Comment by Brennan-Walsh** [comment]
The keycloak login page has been added
![Image](https://github.com/user-attachments/assets/233eda8d-8e01-410c-8d6a-0d96f8c5a5c5)
