### ISSUE TITLE
4.3.2 Add Superset docker to the Mapstack container

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#45]
![image](https://github.com/user-attachments/assets/a612d5f1-7dff-42f3-95a7-38e36952f8b6)

**Comment by Brennan-Walsh** [comment]
The superset container has been added and we can access it here https://mapstack-uat.geoint.africa/analytics/

However the urls is not working correct so we can use the dropdown menu on the right side. 

![Image](https://github.com/user-attachments/assets/ea8a950a-887a-4c83-a9e5-5a1d433e21d4)

**Comment by voogt** [comment]
Hi @Brennan-Walsh I updated the reverse proxy can you please do a git pull and test again?
