### ISSUE TITLE
4.4.6 Printing

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#49]
![image](https://github.com/user-attachments/assets/3ee633e6-a9e4-47df-9245-4a2eafdacfa1)

**Comment by Brennan-Walsh** [comment]
unable to see the print button in the map

**Comment by Brennan-Walsh** [comment]
Want to print this map 
![Image](https://github.com/user-attachments/assets/a3f84394-7313-4707-ad69-2061272a6009)
Here is the print page 
![Image](https://github.com/user-attachments/assets/2f4030bf-70fa-4b7c-b13f-66fbec223c1e)
The out put looks like this and there are no Petrol station on the map 
![Image](https://github.com/user-attachments/assets/af34812a-8766-4a04-9591-35cb33cb091f)

**Comment by voogt** [comment]
@Brennan-Walsh Printing is working now. Can you please confirm
![Image](https://github.com/user-attachments/assets/ab6828ac-1afc-43c6-95b3-61598e93f2ce)

**Comment by Brennan-Walsh** [comment]
The printer button is now working
