### ISSUE TITLE
4.5.1 Apply Custom Mapstack 2.0 Change

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#50]
![image](https://github.com/user-attachments/assets/4a6bb084-fb22-4079-8af9-fe4b927ef6ad)

**Comment by tinashechiraya** [comment]
can I get some context here @mvmaltitz @voogt

**Comment by voogt** [comment]
@tinashechiraya you need to implement all custom work Kartoza has done so far on mapstore with the new version
This was the last document https://docs.google.com/spreadsheets/d/1EJEmtxRLRN9Lt1L9HP8J9wFwa8nXzOD2VTUh9nM4v-s/edit?gid=0#gid=0 I could find it was for testing but this was the custom work

**Comment by voogt** [comment]
@tinashechiraya the recent maps was custom work as well as your sign in page, we also had The Insights Toolbox plugin which was custom

**Comment by voogt** [comment]
@tinashechiraya ignore the first link here is the dev document https://docs.google.com/spreadsheets/d/1KRrjfw_xhj90t3Oig4uB0p-YtQa1HVRAukBS4pBO0oE/edit?gid=0#gid=0
