### ISSUE TITLE
4.5.2 Login Page UI

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#51]
![image](https://github.com/user-attachments/assets/651ceab5-3db8-4b56-8bdd-db44ff79a68b)

**Comment by tinashechiraya** [comment]
![Image](https://github.com/user-attachments/assets/d0e7124b-eee5-42b8-84db-0ed04872853b)

**Comment by Brennan-Walsh** [comment]
this is part of keycloak
