### ISSUE TITLE
5.1 Mapstack Builder Development box updated

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#53]
![image](https://github.com/user-attachments/assets/1585230f-819a-4986-a308-28fc6a788f3f)

**Comment by Brennan-Walsh** [comment]
Kaylan has tested this

**Comment by Brennan-Walsh** [comment]
529286

**Comment by Brennan-Walsh** [comment]
![Image](https://github.com/user-attachments/assets/59482e2b-c8de-4c6d-b6fb-86234a4cc5d9)
