### ISSUE TITLE
1.1.8 New: PgBackRest

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#6]
Performs full, differential or incremental database backups to local or remote repositories
![image](https://github.com/user-attachments/assets/7591f4e0-391c-4b7b-9597-bade9f76e7b3)

**Comment by Brennan-Walsh** [comment]
![Image](https://github.com/user-attachments/assets/f13b695b-3d07-4555-9b6d-87333d719976)

**Comment by Brennan-Walsh** [comment]
Not sure how to test for this one

Here is the error please ask kaylan

**Comment by Brennan-Walsh** [comment]
Kayalan to check if Cron running every morning.  look in read for the location
