### ISSUE TITLE
UX / UI edit button does not go away

### ISSUE THREAD

**Issue by Brennan-Walsh** [kartoza/MapSTACK-2.1#79]

**Comment by Brennan-Walsh** [comment]
Click edit button 
![Image](https://github.com/user-attachments/assets/c814303f-2390-4fa6-8dd0-a3f6c4e84907)
A second position icon appears
![Image](https://github.com/user-attachments/assets/dea6e323-b191-4ee7-af5f-07971ebd2b8f)
after closing the edit table the toolbar stays behind. 
![Image](https://github.com/user-attachments/assets/3ab5fce3-2eb6-4b54-9965-e75d2b5d2267)

**Comment by Brennan-Walsh** [comment]
Dont thing you understood this correctly. We need the edit button. Problem is that when we click on the edit button is seem to open a second navigation button

**Comment by voogt** [comment]
Hi @Brennan-Walsh apologies  please use this url to this https://mapstack-qa.geoint.africa/mapitqa/ as https://mapstack-qa.geoint.africa/mapit3/ is outdated

**Comment by Brennan-Walsh** [comment]
Ok I have just checked with the new url.  The two ticket error are still precent.




Brennan Walsh

Senior Geospatial Data Engineer and Analyst
Direct: +27 83 694 8572<tel:+27%20836948572>
Email: ***@***.******@***.***>
Web: www.geoint.africa <https://geoint.africa/>
View our privacy policy here<https://geoint.africa/wp-content/uploads/2023/07/GeoINT_Privacy_Policy_23.pdf>
View our PAIA and POPIA here<https://geoint.africa/wp-content/uploads/2023/07/PAIA-Manual.pdf>
[LinkdIn Logo]<https://www.linkedin.com/company/geo-intelligence-corp/>
[Geoint Company Logo]

**Comment by voogt** [comment]
Hi @Brennan-Walsh can you do a hard refresh or open in incognito mode?
https://github.com/user-attachments/assets/b7aa187d-22a8-488e-bab8-169157c23c0d

**Comment by Brennan-Walsh** [comment]
Should we get a  quick call to look at these two issues. I have  few minutes now

Tried the refresh but not working this simple.

Brennan Walsh

Senior Geospatial Data Engineer and Analyst
Direct: +27 83 694 8572<tel:+27%20836948572>
Email: ***@***.******@***.***>
Web: www.geoint.africa <https://geoint.africa/>
View our privacy policy here<https://geoint.africa/wp-content/uploads/2023/07/GeoINT_Privacy_Policy_23.pdf>
View our PAIA and POPIA here<https://geoint.africa/wp-content/uploads/2023/07/PAIA-Manual.pdf>
[LinkdIn Logo]<https://www.linkedin.com/company/geo-intelligence-corp/>
[Geoint Company Logo]

**Comment by voogt** [comment]
Hi @Brennan-Walsh we can do a quick meeting. I am free this afternoon or we can do a quick checkin tomorrow morning

**Comment by Brennan-Walsh** [comment]
This is working now
