### ISSUE TITLE
Geoserver logout button.

### ISSUE THREAD

**Issue by Brennan-Walsh** [kartoza/MapSTACK-2.1#82]

**Comment by Brennan-Walsh** [comment]
being able to logout from geoserver would be useful so that you can login as a differnt users and see what layers they have access to. Currently you have to move to the mapstack frameend in or to force the logout. 

![Image](https://github.com/user-attachments/assets/eb46a59e-9a77-4aad-bda0-fbaa68082cb3)

**Comment by mvmaltitz** [comment]
@Brennan-Walsh 

This is a known error with Geoserver, I am not sure it is something we can change

**Comment by Brennan-Walsh** [comment]
ok we will have to part this one
