### ISSUE TITLE
Geoprocessing Tool

### ISSUE THREAD

**Issue by Brennan-Walsh** [kartoza/MapSTACK-2.1#83]

**Comment by Brennan-Walsh** [comment]
Currently the tools is blank

![Image](https://github.com/user-attachments/assets/8b404b8d-8595-4f61-9c04-6b09d9dcb859)

**Comment by Brennan-Walsh** [comment]
Zoo Service Unavailable 
![Image](https://github.com/user-attachments/assets/02e3d4f4-c56c-4344-adea-bdc8a18a1992)

**Comment by Brennan-Walsh** [comment]
The tool is showing up after a reboot. But no results yet

![Image](https://github.com/user-attachments/assets/cf4d69b6-a9b4-4fe9-a5b7-136243d4192f)

**Comment by Brennan-Walsh** [comment]
Which Tables store the results 

![Image](https://github.com/user-attachments/assets/91a247b1-1055-48b1-b9c0-d6c2a46048e9)
 Currently no able to see where the rusults are stored. 

![Image](https://github.com/user-attachments/assets/71d4b3e7-817b-4c7c-9edf-b343f085a2c7)

**Comment by Brennan-Walsh** [comment]
![Image](https://github.com/user-attachments/assets/710afc35-10d5-4d50-903d-3d6e3265daba)

![Image](https://github.com/user-attachments/assets/fd205bf2-5907-4dff-84ca-16ab159f7075)

**Comment by voogt** [comment]
@Brennan-Walsh geoprocessing tool is working now. 
![Image](https://github.com/user-attachments/assets/abee95a4-7a61-4d14-b2fc-b8ea65aa1ff1)

**Comment by Brennan-Walsh** [comment]
Thank you i will test this all shortly

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Brennan-Walsh** [comment]
I have check this using the admin account and the tool is now working

**Comment by Brennan-Walsh** [comment]
Thank you thin is now working.

Brennan Walsh

Senior Geospatial Data Engineer and Analyst
Direct: +27 83 694 8572<tel:+27%20836948572>
Email: ***@***.******@***.***>
Web: www.geoint.africa <https://geoint.africa/>
View our privacy policy here<https://geoint.africa/wp-content/uploads/2023/07/GeoINT_Privacy_Policy_23.pdf>
View our PAIA and POPIA here<https://geoint.africa/wp-content/uploads/2023/07/PAIA-Manual.pdf>
[LinkdIn Logo]<https://www.linkedin.com/company/geo-intelligence-corp/>
[Geoint Company Logo]
