### ISSUE TITLE
1.3.1 Upgrade 2.25.3 minimum

### ISSUE THREAD

**Issue by mvmaltitz** [kartoza/MapSTACK-2.1#9]
Latest Stable version of Geoserver and extensions that match it
![image](https://github.com/user-attachments/assets/4b1a8b57-413d-452e-a148-d291eef620da)

**Comment by Brennan-Walsh** [comment]
https://mapstack-qa.geoint.africa/geoserver/web/wicket/bookmarkable/org.geoserver.web.admin.StatusPage?40&filter=false
